base_url = "https://svsats.github.io/satscoinsv_website/"
compile_sass = true
title = "after-dark"
description = "A robust, elegant dark theme"
generate_feeds = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

build_search_index = true 

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[search]
index_format = "elasticlunr_json"

[extra]
author = "Satscoin"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "Empieza con tu libertad tecnológica"
codeblock = true
latex = true
enable_search = true

+++
title = "Mi primer post"
date = 2024-06-08
categories = ["General"]
tags = ["inicio"]
+++

¡Este es el contenido de mi primer post!

+++
paginate_by = 5
+++

# ¡Bienvenido a SatsCoinSV!

Aquí encontrarás mis publicaciones sobre Bitcoin, Nostr y tecnología.
